import { Plus, BarChart2, FileBarChart, Shield, Scale, Download } from 'lucide-react';

export function Reports() {
  return (
    <div className="p-container-margin max-w-5xl mx-auto min-h-screen">
      {/* Page Header */}
      <div className="flex justify-between items-end mb-8">
        <div>
          <h2 className="text-metric-display font-medium text-on-surface tracking-tight">Reports</h2>
          <p className="text-body-main text-on-surface-variant mt-1">Manage and download your organization's compliance and governance audits.</p>
        </div>
        <button className="h-9 px-4 bg-primary text-on-primary rounded-lg font-section-header flex items-center gap-2 hover:bg-primary/90 transition-all active:scale-95 shadow-sm">
          <Plus className="w-4 h-4 text-on-primary" strokeWidth={3} />
          Generate report
        </button>
      </div>

      {/* Reports Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-stack_gap_md">
        <ReportCard 
          title="Monthly compliance report" 
          lastRun="Last: 1 May 2026" 
          size="2.4 MB" 
          icon={<BarChart2 className="w-7 h-7 text-primary fill-primary/10" />} 
          iconBg="bg-primary/5" 
        />
        <ReportCard 
          title="Data quality summary" 
          lastRun="Last: 15 Apr 2026" 
          size="1.8 MB" 
          icon={<FileBarChart className="w-7 h-7 text-secondary fill-secondary/10" />} 
          iconBg="bg-secondary/5" 
        />
        <ReportCard 
          title="Security access audit" 
          lastRun="Last: 28 Apr 2026" 
          size="3.1 MB" 
          icon={<Shield className="w-7 h-7 text-tertiary fill-tertiary/10" />} 
          iconBg="bg-tertiary-container/10" 
        />
        <ReportCard 
          title="Governance overview" 
          lastRun="Last: 10 May 2026" 
          size="2.4 MB" 
          icon={<Scale className="w-7 h-7 text-primary fill-primary/10" />} 
          iconBg="bg-primary/5" 
        />
      </div>

      {/* Recent Activity Table */}
      <div className="mt-12 bg-surface-container-lowest border border-precision border-outline-variant rounded-xl overflow-hidden shadow-sm">
        <div className="px-card-padding py-4 border-b border-precision border-outline-variant flex justify-between items-center bg-transparent">
          <h3 className="font-section-header text-section-header text-on-surface font-medium">Recent Generation Log</h3>
          <span className="text-label-caps text-on-surface-variant bg-surface-container-low px-2 py-1 rounded tracking-wide">Last 24 Hours</span>
        </div>
        
        <div className="overflow-x-auto">
          <table className="w-full text-left zebra-table">
            <thead className="bg-surface-container-low">
              <tr>
                <th className="px-card-padding py-3 font-label-caps text-label-caps text-on-surface-variant uppercase">Report Name</th>
                <th className="px-card-padding py-3 font-label-caps text-label-caps text-on-surface-variant uppercase">Generated By</th>
                <th className="px-card-padding py-3 font-label-caps text-label-caps text-on-surface-variant uppercase">Status</th>
                <th className="px-card-padding py-3 font-label-caps text-label-caps text-on-surface-variant uppercase">Time</th>
              </tr>
            </thead>
            <tbody className="text-body-main divide-y border-precision divide-outline-variant/30">
              <LogEntry name="Compliance_v2_Draft" user="System Automator" status="Success" time="10:45 AM" />
              <LogEntry name="Weekly_Data_Sanity" user="Admin User" status="Success" time="09:12 AM" />
              <LogEntry name="Security_Incident_Log" user="Security Bot" status="In Progress" time="08:55 AM" />
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function ReportCard({ title, lastRun, size, icon, iconBg }: any) {
  return (
    <div className="bg-surface-container-lowest border border-precision border-outline-variant rounded-xl p-card-padding flex flex-col justify-between group hover:border-primary/30 transition-all duration-300 shadow-sm relative overflow-hidden">
      <div className="flex items-start justify-between mb-4 relative z-10">
        <div className={`w-12 h-12 rounded-lg flex items-center justify-center ${iconBg}`}>
          {icon}
        </div>
        <span className="px-2 py-1 bg-surface-container rounded text-label-caps font-label-caps text-on-surface-variant tracking-wide font-medium">
          {size}
        </span>
      </div>
      <div className="relative z-10">
        <h3 className="text-section-header font-medium text-on-surface">{title}</h3>
        <p className="text-body-main text-on-surface-variant mt-1">{lastRun}</p>
      </div>
      <div className="mt-6 pt-4 border-t border-precision border-outline-variant/30 flex justify-end relative z-10">
        <button className="h-9 px-4 bg-white border border-precision border-outline-variant text-on-surface rounded-lg font-body-main text-body-main flex items-center gap-2 hover:bg-surface-container-low transition-colors shadow-[0_1px_2px_rgba(0,0,0,0.02)]">
          <Download className="w-4 h-4 text-on-surface-variant" />
          Download PDF
        </button>
      </div>
      {/* Subtle hover gradient */}
      <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none"></div>
    </div>
  );
}

function LogEntry({ name, user, status, time }: any) {
  const isSuccess = status === 'Success';
  
  return (
    <tr className="hover:bg-surface-container-low/50 transition-colors">
      <td className="px-card-padding py-4 font-medium text-on-surface">{name}</td>
      <td className="px-card-padding py-4 text-on-surface-variant">{user}</td>
      <td className="px-card-padding py-4">
        {isSuccess ? (
          <span className="px-2 py-0.5 rounded-full bg-green-100 text-green-700 text-[11px] font-bold">Success</span>
        ) : (
          <span className="px-2 py-0.5 rounded-full bg-orange-100 text-orange-700 text-[11px] font-bold">In Progress</span>
        )}
      </td>
      <td className="px-card-padding py-4 text-on-surface-variant">{time}</td>
    </tr>
  );
}
